### ISSUE TITLE
Consume Fruit as shared library from source via cmake

### ISSUE THREAD

**Issue by Hugozys** [google/fruit#121]
I noticed there are a couple of related issues which might be similar to the problem that I met:
#116 
#62 

I apologized if this issue is duplicated, but I can't seem to find an answer to solve my confusion from the discussion of these issues.

So I know a usual way for an application to consume fruit is by first installing the pre-built binary on the system and then just use `-lfruit` if using Makefile directly or via the cmake module provided in the source if using cmake. I tried not to require the user to install fruit first on their system.
So what I did was include fruit source as a submodule and then when user run cmake to build the application, it first builds fruit as a shared object and then link it to the application. To make things simple, I want to use the classic hello.cc present in the example to illustrate the problem I met.

Here's my demo project structure:
```
.
├── CMakeLists.txt
├── libs
│   └── fruit (include fruit source)
 |
└── srcs
    └── hello.cc
```
Here's my CMakeList.txt:
```
cmake_minimum_required(VERSION 3.1...3.18)

if (${CMAKE_VERSION} VERSION_LESS 3.12)
    cmake_policy(VERSION ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}})
endif()


project(hello VERSION 0.1.0
             DESCRIPTION "Hello World"
             LANGUAGES CXX)

# set your cmake variables

set(CMAKE_CXX_STANDARD_17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release)
set(FRUIT_USES_BOOST False)
set(FRUIT_TESTS_USE_PRECOMPILED_HEADERS OFF)
set(FRUIT_HEADER_DIR "${PROJECT_SOURCE_DIR}/libs/fruit/include/")

add_subdirectory("${PROJECT_SOURCE_DIR}/libs/fruit")
add_executable(hello srcs/hello.cc)
target_include_directories(hello PUBLIC "${FRUIT_HEADER_DIR}")
target_link_libraries(hello PRIVATE fruit)
```
However I encountered the following build error when I run: `mkdir build && cd build && cmake .. && make`
```
Scanning dependencies of target fruit
[  0%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/memory_pool.cpp.o
[ 11%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/binding_normalization.cpp.o
[ 22%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/demangle_type_name.cpp.o
[ 22%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/component.cpp.o
[ 33%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/fixed_size_allocator.cpp.o
[ 33%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/injector_storage.cpp.o
[ 44%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/normalized_component_storage.cpp.o
[ 44%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/normalized_component_storage_holder.cpp.o
[ 55%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/semistatic_map.cpp.o
[ 55%] Building CXX object libs/fruit/src/CMakeFiles/fruit.dir/semistatic_graph.cpp.o
[ 66%] Linking CXX shared library libfruit.so
[ 66%] Built target fruit
Scanning dependencies of target HELLO
[ 66%] Building CXX object CMakeFiles/HELLO.dir/srcs/hello.cc.o
In file included from /root/demo/libs/fruit/include/fruit/impl/meta/algos.h:20,
                 from /root/demo/libs/fruit/include/fruit/impl/meta/component.h:23,
                 from /root/demo/libs/fruit/include/fruit/impl/data_structures/fixed_size_allocator.h:21,
                 from /root/demo/libs/fruit/include/fruit/impl/injector/injector_storage.h:21,
                 from /root/demo/libs/fruit/include/fruit/impl/component_functors.defn.h:24,
                 from /root/demo/libs/fruit/include/fruit/component.h:25,
                 from /root/demo/libs/fruit/include/fruit/fruit.h:27,
                 from /root/demo/srcs/hello.cc:1:
/root/demo/libs/fruit/include/fruit/impl/fruit-config.h:20:10: fatal error: fruit/impl/fruit-config-base.h: No such file or directory
   20 | #include <fruit/impl/fruit-config-base.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/HELLO.dir/build.make:63: CMakeFiles/HELLO.dir/srcs/hello.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: CMakeFiles/HELLO.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I saw #62 mentioned the same problem but it was on an embedded device. I was just trying to make this work on `Ubuntu 20.04` and `Arch Linux`. 

In the response to that issue. poletti mentioned that the missing header file is auto generated and we have to run cmake first. I thought I ensured that the fruit library got built first by having the `add_subdirectory` function. I might be misunderstanding how to build fruit as a shared library. Can I get some help on this?

**Comment by tt4g** [comment]
It seems that `fruit-config-base.h` is generated in `${Fruit_BINARY_DIR}/include/fruit/impl` but `hello` project can not find it.
This is because `fruit` do not define `INTERFACE_INCLUDE_DIRECTORIES` by `target_include_directories()`.

Should you add `${Fruit_BINARY_DIR}/include` to `hello` include directories.

NOTE: `Fruit_BINARY_DIR` is defined by `project()` command that it is undefined before `add_subdirectory("${PROJECT_SOURCE_DIR}/libs/fruit")`.

```diff
set(CMAKE_CXX_STANDARD_17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release)
set(FRUIT_USES_BOOST False)
set(FRUIT_TESTS_USE_PRECOMPILED_HEADERS OFF)
- set(FRUIT_HEADER_DIR "${PROJECT_SOURCE_DIR}/libs/fruit/include/")

add_subdirectory("${PROJECT_SOURCE_DIR}/libs/fruit")
+ set(FRUIT_HEADER_DIR "${PROJECT_SOURCE_DIR}/libs/fruit/include/" "${Fruit_BINARY_DIR}/include}")
add_executable(hello srcs/hello.cc)
target_include_directories(hello PUBLIC "${FRUIT_HEADER_DIR}")
```

**Comment by Hugozys** [comment]
It worked like a charm! I'm totally new to CMake so didn't know the INTERFACE_INCLUDE_DIRECTORIES before. Thank you so much! Will close the ticket now.

**Comment by Hugozys** [comment]
@tt4g I hate to disappoint you, but I just found out the reason why it worked was because I installed pre-built binary already on my arch & ubuntu XD. If I removed the pre-built binary and run cmake with suggested changes. I got the same error. This also reflected in my CI process.

**Comment by tt4g** [comment]
Sorry. My mistake.
It had an unnecessary brace on it.

The compiler should find the header file with the following modifications:

```diff
add_subdirectory("${PROJECT_SOURCE_DIR}/libs/fruit")
- set(FRUIT_HEADER_DIR "${PROJECT_SOURCE_DIR}/libs/fruit/include/" "${Fruit_BINARY_DIR}/include}")
+ set(FRUIT_HEADER_DIR "${PROJECT_SOURCE_DIR}/libs/fruit/include/" "${Fruit_BINARY_DIR}/include")
```

**Comment by Hugozys** [comment]
Ah! I didn't notice that either. Now it worked!! Thanks for the help again!

**Comment by poletti-marco** [comment]
@tt4g : thanks so much for your help here! Much appreciated!
