### ISSUE TITLE
fatal error C1001: An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by BachiScience** [google/fruit#60]
I get a fatal error after trying to compile my project. 
I have build fruit with Visual Studio 15 2017 (like it is described in git) and i do not used boost for building fruit (fruit version v3.1.0)

Error code:
...\lib\fruit\include\fruit/impl/injector/injector_storage.defn.h(504): fatal error C1001: An internal error has occurred in the compiler.

Procedure:
CMakeSettings.json:
{
    // See https://go.microsoft.com//fwlink//?linkid=834763 for more information about this file.
    "configurations": [
        {
            "name": "x86-Debug",
            "generator": "Visual Studio 15 2017",
            "configurationType": "Release",
            "buildRoot": "C:\\Users\\Bachelorarbeit\\Desktop\\Fruit3\\fruit\\FruitBuild",
            "cmakeCommandArgs": "-DFRUIT_USES_BOOST=False -DCMAKE_BUILD_TYPE=Release -DFRUIT_ADDITIONAL_CXX_FLAGS=/Z7",
            "buildCommandArgs": "-m -v:minimal"
        }
    ]
}
After that:
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Bachelorarbeit/Desktop/Fruit/fruit"

After that build with:
CMake -> Build All
Successfully build! 0 errors!

When i try to compile i get the error code.

I hope there is a workaround or a smart solution for this error.
Happy new year!

**Comment by poletti-marco** [comment]
Hi, thanks for reporting this. It seems to be a regression in MSVC.
Fruit 3.1.0 worked with MSVC 2017 v15.4.4:
https://ci.appveyor.com/project/poletti-marco/fruit/build/1.0.174/job/gvkl8u44wclp48b9

But with MSVC 2017 v15.5.2 it fails:
https://ci.appveyor.com/project/poletti-marco/fruit/build/1.0.175/job/ackovky4bj8yp4rd

Once I'm back from vacation I'll report the bug to MS and see if I can find a workaround for this for the short term.

**Comment by poletti-marco** [comment]
Hi, sorry for the delay.
I've now filed the MSVC bug:
https://developercommunity.visualstudio.com/content/problem/182074/internal-compiler-error-in-msvc-2017-155.html

However I'm not sure how long it will take for MS to fix that bug, so I've also released Fruit 3.1.1 with a workaround.
Please try again with 3.1.1, it works now.
